Add example for TI 74HC595 shift registers
Rahix/avr-hal pull request #380
Opened 2022-12-13 16:00 UTC by bclarke123

Example code to use a 595 shift register to light up 8 LEDs from 3 wires + 5V/GND, link to wiring diagrams and hardware tutorial is in the source file.  All feedback welcome, thanks for this awesome project!

2022-12-13 23:09 UTC, Rahix requested changes
Hey, thanks for the contribution!  Please check the CI failure.  I think you used the wrong kind of doc-comment at the top of the file.

2022-12-13 23:45 UTC, bclarke123 commented
Should be fixed I believe, thanks!

2022-12-14 21:19 UTC, Rahix approved these changes

2022-12-14 21:20 UTC, merged

2022-12-14 21:20 UTC, Rahix commented
Thanks!