Add support for ATmega8
Rahix/avr-hal pull request #384
Opened 2022-12-23 23:09 UTC by Rutherther

Adds support for ATmega8 (https://github.com/Rahix/avr-device/pull/112 has to be resolved first for this to work correctly).

ATmega8 is more challenging, because it does not work like the atmegas that were already implemented in some ways
  1. EEPROM does not have modes (erase, erase and write), completely different mechanism is required.
  2. WDT registers have different names "s" is missing from wdtcsr.
  3. Does not have DIDR for ADCs
  4. USART does not have "0" at end. It's just USART, not USART0. It has registers UBRRL, UBRRH instead of just one UBRR. I don't think it's possible to merge into just one register using patches as the UBRRH is shared with UCSRC and it's not directly next to UBRRL.

1. I implemented a new macro that is named `impl_eeprom_atmega_old`. I am not sure if this name fits.

2. I added paste macro and passed in a string name of the register

3. I created a no_didr macro that does not contain anything in the relevant method. I don't think there is anything else to be done in that method, but I may be wrong here. I have not used ADCs that much.

4. as ATmega8 looks very specific regarding USART, I decided to not even create a macro, but instead implement it directly in atmega-hal/wdt.rs. There is a few differences to usart macro, namely UCSRC and UBRRH are functions, UCSRC has to have set URSEL to one (that says UCSRC should be set instead of UBRRH as they share the same location in memory). UBRR is set by UBRRH and UBRRL instead of just UBRR.

What do you think about these changes? Do you have better idea how to implement ATmega8?

I have tested EEPROM, USART, ADCs (and using ports of course) so far. I will try to test the rest in short time.

2023-01-05 16:40 UTC, Rahix commented
I released a new version of avr-device ([0.5.0](https://github.com/Rahix/avr-device/releases/tag/v0.5.0)) and already updated avr-hal for it (#389).  Your ATmega8 patches are included in the release.  You can rebase your commits ontop of latest `main` to move this PR forward.

2023-01-05 18:41 UTC, Rutherther commented
Thank you for that.

> You can rebase your commits ontop of latest main to move this PR forward.
So, this PR is *functionally* already done. The thing is that I am not happy with the design choices I made, do you have any better idea on how to proceed?

I am mainly not happy about the watchdog panic!()'s and usart without a proper macro.

2023-02-23 03:03 UTC, Rahix requested changes
Hey, sorry for only getting back to this PR now...  Thanks for your work on ATmega8 support, anyway!

I've left some comments below, regarding the design topics you mentioned.  For USART I do not see a great solution right now either, especially considering additional requirements which now came up for ATmega128A in #397...

2023-02-23 03:06 UTC, Rahix commented on avr-hal-generic/src/adc.rs
> +macro_rules! impl_adc_no_didr {
<details>
<summary><b>Expand for full patch ontop of your PR</b></summary>

```diff
From 8298ceaed62dc82f3161d818cabd37efef913289 Mon Sep 17 00:00:00 2001
From: Rahix <rahix@rahix.de>
Date: Thu, 23 Feb 2023 04:04:19 +0100
Subject: [PATCH] Factor second ADC macro back into a single one

---
 avr-hal-generic/src/adc.rs | 102 ++-----------------------------------
 mcu/atmega-hal/src/adc.rs  |  14 ++---
 2 files changed, 11 insertions(+), 105 deletions(-)

diff --git a/avr-hal-generic/src/adc.rs b/avr-hal-generic/src/adc.rs
index d2df5ceb8e..046b456d93 100644
--- a/avr-hal-generic/src/adc.rs
+++ b/avr-hal-generic/src/adc.rs
@@ -214,7 +214,7 @@ macro_rules! impl_adc {
         pins: {
             $(
                 $(#[$pin_attr:meta])*
-                $pin:ty: ($pin_channel:expr, $didr:ident::$didr_method:ident),
+                $pin:ty: ($pin_channel:expr$(, $didr:ident::$didr_method:ident)?),
             )+
         },
         $(channels: {
@@ -264,7 +264,9 @@ macro_rules! impl_adc {
                 match channel {
                     $(
                         $(#[$pin_attr])*
-                        x if x == $pin_channel => self.$didr.modify(|_, w| w.$didr_method().set_bit()),
+                        x if x == $pin_channel => {
+                            $(self.$didr.modify(|_, w| w.$didr_method().set_bit());)?
+                        }
                     )+
                     _ => unreachable!(),
                 }
@@ -304,99 +306,3 @@ macro_rules! impl_adc {
         )*)?
     };
 }
-
-#[macro_export]
-macro_rules! impl_adc_no_didr {
-    (
-        hal: $HAL:ty,
-        peripheral: $ADC:ty,
-        settings: $Settings:ty,
-        apply_settings: |$settings_periph_var:ident, $settings_var:ident| $apply_settings:block,
-        channel_id: $Channel:ty,
-        set_channel: |$periph_var:ident, $chan_var:ident| $set_channel:block,
-        pins: {
-            $(
-                $(#[$pin_attr:meta])*
-                $pin:ty: $pin_channel:expr,
-            )*
-        },
-        $(channels: {
-            $(
-                $(#[$channel_attr:meta])*
-                $channel_ty:ty: $channel:expr,
-            )*
-        },)?
-    ) => {
-        impl $crate::adc::AdcOps<$HAL> for $ADC {
-            type Channel = $Channel;
-            type Settings = $Settings;
-
-            #[inline]
-            fn raw_init(&mut self, settings: Self::Settings) {
-                let $settings_periph_var = self;
-                let $settings_var = settings;
-
-                $apply_settings
-            }
-
-            #[inline]
-            fn raw_read_adc(&self) -> u16 {
-                self.adc.read().bits()
-            }
-
-            #[inline]
-            fn raw_is_converting(&self) -> bool {
-                self.adcsra.read().adsc().bit_is_set()
-            }
-
-            #[inline]
-            fn raw_start_conversion(&mut self) {
-                self.adcsra.modify(|_, w| w.adsc().set_bit());
-            }
-
-            #[inline]
-            fn raw_set_channel(&mut self, channel: Self::Channel) {
-                let $periph_var = self;
-                let $chan_var = channel;
-
-                $set_channel
-            }
-
-            #[inline]
-            fn raw_enable_channel(&mut self, channel: Self::Channel) {
-            }
-        }
-
-        $(
-        $(#[$pin_attr])*
-        impl $crate::adc::AdcChannel<$HAL, $ADC> for $crate::port::Pin<$crate::port::mode::Analog, $pin> {
-            #[inline]
-            fn channel(&self) -> $Channel {
-                $pin_channel
-            }
-        }
-        )+
-
-        $($(
-        $(#[$channel_attr])*
-        impl $crate::adc::AdcChannel<$HAL, $ADC> for $channel_ty {
-            #[inline]
-            fn channel(&self) -> $Channel {
-                $channel
-            }
-        }
-
-        /// Convert this channel into a generic "[`Channel`][adc-channel]" type.
-        ///
-        /// The generic channel type can be used to store multiple channels in an array.
-        ///
-        /// [adc-channel]: crate::adc::Channel
-        $(#[$channel_attr])*
-        impl $channel_ty {
-            pub fn into_channel(self) -> $crate::adc::Channel<$HAL, $ADC> {
-                crate::adc::Channel::new(self)
-            }
-        }
-        )*)?
-    };
-}
diff --git a/mcu/atmega-hal/src/adc.rs b/mcu/atmega-hal/src/adc.rs
index 5412019047..19d3372b95 100644
--- a/mcu/atmega-hal/src/adc.rs
+++ b/mcu/atmega-hal/src/adc.rs
@@ -258,7 +258,7 @@ avr_hal_generic::impl_adc! {
 }
 
 #[cfg(any(feature = "atmega8"))]
-avr_hal_generic::impl_adc_no_didr! {
+avr_hal_generic::impl_adc! {
     hal: crate::Atmega,
     peripheral: crate::pac::ADC,
     settings: AdcSettings,
@@ -268,12 +268,12 @@ avr_hal_generic::impl_adc_no_didr! {
         peripheral.admux.modify(|_, w| w.mux().variant(id));
     },
     pins: {
-        port::PC0: crate::pac::adc::admux::MUX_A::ADC0,
-        port::PC1: crate::pac::adc::admux::MUX_A::ADC1,
-        port::PC2: crate::pac::adc::admux::MUX_A::ADC2,
-        port::PC3: crate::pac::adc::admux::MUX_A::ADC3,
-        port::PC4: crate::pac::adc::admux::MUX_A::ADC4,
-        port::PC5: crate::pac::adc::admux::MUX_A::ADC5,
+        port::PC0: (crate::pac::adc::admux::MUX_A::ADC0),
+        port::PC1: (crate::pac::adc::admux::MUX_A::ADC1),
+        port::PC2: (crate::pac::adc::admux::MUX_A::ADC2),
+        port::PC3: (crate::pac::adc::admux::MUX_A::ADC3),
+        port::PC4: (crate::pac::adc::admux::MUX_A::ADC4),
+        port::PC5: (crate::pac::adc::admux::MUX_A::ADC5),
     },
     channels: {
         #[cfg(feature = "enable-extra-adc")]
-- 
2.39.0
```

</details>

2023-02-23 03:07 UTC, Rahix commented on avr-hal-generic/src/wdt.rs
> +        $crate::paste::paste! {
<details>
<summary><b>Expand for full patch ontop of your PR</b></summary>

```diff
From 84ae184fe00c3d119fe14b719f87d0a206f57120 Mon Sep 17 00:00:00 2001
From: Rahix <rahix@rahix.de>
Date: Thu, 23 Feb 2023 02:39:42 +0100
Subject: [PATCH] Cleanup the WDT macro so it does not need paste!()

---
 avr-hal-generic/src/wdt.rs | 122 ++++++++++++++++++-------------------
 mcu/atmega-hal/src/wdt.rs  |   4 +-
 2 files changed, 63 insertions(+), 63 deletions(-)

diff --git a/avr-hal-generic/src/wdt.rs b/avr-hal-generic/src/wdt.rs
index 6ed085a573..94d0a2d7ed 100644
--- a/avr-hal-generic/src/wdt.rs
+++ b/avr-hal-generic/src/wdt.rs
@@ -85,69 +85,69 @@ macro_rules! impl_wdt {
         hal: $HAL:ty,
         peripheral: $WDT:ty,
         mcusr: $MCUSR:ty,
-        wdtcsr_name: $WDTCSR:expr,
+        wdtcsr_name: $wdtcsr:ident,
         timeout: |$to:ident, $w:ident| $to_match:expr,
     ) => {
-        $crate::paste::paste! {
-            impl $crate::wdt::WdtOps<$HAL> for $WDT {
-                type MCUSR = $MCUSR;
-
-                #[inline]
-                fn raw_init(&mut self, m: &Self::MCUSR) {
-                    /// If a prior reset was provided by the watchdog, the WDRF in MCUSR would be set,
-                    /// so WDRF is also cleared to allow for re-enabling the watchdog.
-                    m.modify(|_, w| w.wdrf().clear_bit());
-                }
-
-                #[inline]
-                fn raw_start(&mut self, timeout: Timeout) -> Result<(), ()> {
-                    // The sequence for changing time-out configuration is as follows:
-                    //
-                    //     1. In the same operation, write a logic one to the Watchdog change enable bit
-                    //        (WDCE) and WDE. A logic one must be written to WDE regardless of the
-                    //        previous value of the WDE bit.
-                    //     2. Within the next four clock cycles, write the WDE and Watchdog prescaler
-                    //        bits (WDP) as desired, but with the WDCE bit cleared. This must be done in
-                    //        one operation.
-                    $crate::avr_device::interrupt::free(|_| {
-                        // Reset the watchdog timer.
-                        self.raw_feed();
-                        // Enable watchdog configuration mode.
-                        self.[<$WDTCSR>].modify(|_, w| w.wdce().set_bit().wde().set_bit());
-                        // Enable watchdog and set interval.
-                        self.[<$WDTCSR>].write(|w| {
-                            let $to = timeout;
-                            let $w = w;
-                            ($to_match).wde().set_bit().wdce().clear_bit()
-                        });
-
-                        Ok(())
-                    })
-                }
-
-                #[inline]
-                fn raw_feed(&mut self) {
-                    avr_device::asm::wdr();
-                }
-
-                #[inline]
-                fn raw_stop(&mut self) {
-                    // The sequence for clearing WDE is as follows:
-                    //
-                    //     1. In the same operation, write a logic one to the Watchdog change enable bit
-                    //        (WDCE) and WDE. A logic one must be written to WDE regardless of the
-                    //        previous value of the WDE bit.
-                    //     2. Within the next four clock cycles, clear the WDE and WDCE bits.
-                    //        This must be done in one operation.
-                    $crate::avr_device::interrupt::free(|_| {
-                        // Reset the watchdog timer.
-                        self.raw_feed();
-                        // Enable watchdog configuration mode.
-                        self.[<$WDTCSR>].modify(|_, w| w.wdce().set_bit().wde().set_bit());
-                        // Disable watchdog.
-                        self.[<$WDTCSR>].reset();
-                    })
-                }
+        impl $crate::wdt::WdtOps<$HAL> for $WDT {
+            type MCUSR = $MCUSR;
+
+            #[inline]
+            fn raw_init(&mut self, m: &Self::MCUSR) {
+                /// If a prior reset was provided by the watchdog, the WDRF in MCUSR would be set,
+                /// so WDRF is also cleared to allow for re-enabling the watchdog.
+                m.modify(|_, w| w.wdrf().clear_bit());
+            }
+
+            #[inline]
+            fn raw_start(&mut self, timeout: Timeout) -> Result<(), ()> {
+                // The sequence for changing time-out configuration is as follows:
+                //
+                //     1. In the same operation, write a logic one to the Watchdog change enable bit
+                //        (WDCE) and WDE. A logic one must be written to WDE regardless of the
+                //        previous value of the WDE bit.
+                //     2. Within the next four clock cycles, write the WDE and Watchdog prescaler
+                //        bits (WDP) as desired, but with the WDCE bit cleared. This must be done in
+                //        one operation.
+                $crate::avr_device::interrupt::free(|_| {
+                    // Reset the watchdog timer.
+                    self.raw_feed();
+                    // Enable watchdog configuration mode.
+                    self.$wdtcsr
+                        .modify(|_, w| w.wdce().set_bit().wde().set_bit());
+                    // Enable watchdog and set interval.
+                    self.$wdtcsr.write(|w| {
+                        let $to = timeout;
+                        let $w = w;
+                        ($to_match).wde().set_bit().wdce().clear_bit()
+                    });
+
+                    Ok(())
+                })
+            }
+
+            #[inline]
+            fn raw_feed(&mut self) {
+                avr_device::asm::wdr();
+            }
+
+            #[inline]
+            fn raw_stop(&mut self) {
+                // The sequence for clearing WDE is as follows:
+                //
+                //     1. In the same operation, write a logic one to the Watchdog change enable bit
+                //        (WDCE) and WDE. A logic one must be written to WDE regardless of the
+                //        previous value of the WDE bit.
+                //     2. Within the next four clock cycles, clear the WDE and WDCE bits.
+                //        This must be done in one operation.
+                $crate::avr_device::interrupt::free(|_| {
+                    // Reset the watchdog timer.
+                    self.raw_feed();
+                    // Enable watchdog configuration mode.
+                    self.$wdtcsr
+                        .modify(|_, w| w.wdce().set_bit().wde().set_bit());
+                    // Disable watchdog.
+                    self.$wdtcsr.reset();
+                })
             }
         }
     };
diff --git a/mcu/atmega-hal/src/wdt.rs b/mcu/atmega-hal/src/wdt.rs
index 1fc6fc38e6..9840a89e0a 100644
--- a/mcu/atmega-hal/src/wdt.rs
+++ b/mcu/atmega-hal/src/wdt.rs
@@ -8,7 +8,7 @@ avr_hal_generic::impl_wdt! {
     hal: crate::Atmega,
     peripheral: crate::pac::WDT,
     mcusr: crate::pac::cpu::MCUSR,
-    wdtcsr_name: "wdtcsr",
+    wdtcsr_name: wdtcsr,
     timeout: |to, w| match to {
         Timeout::Ms16 => w.wdpl().cycles_2k_512k(),
         Timeout::Ms32 => w.wdpl().cycles_4k_1024k(),
@@ -28,7 +28,7 @@ avr_hal_generic::impl_wdt! {
     hal: crate::Atmega,
     peripheral: crate::pac::WDT,
     mcusr: crate::pac::cpu::MCUCSR,
-    wdtcsr_name: "wdtcr",
+    wdtcsr_name: wdtcr,
     timeout: |to, w| match to {
         Timeout::Ms16 => w.wdpl().cycles_16k(),
         Timeout::Ms32 => w.wdpl().cycles_32k(),
-- 
2.39.0
```

</details>

2023-02-23 18:48 UTC, Rutherther commented on avr-hal-generic/src/wdt.rs
> +        $crate::paste::paste! {
Oh, right, I am a newbie in Rust, so I wasn't aware this was a thing.

2023-02-23 18:51 UTC, Rutherther commented
Thank you for these comments, it's no problem at all that you could get to this PR now and not sooner. I think I have made the changes you suggested.

2023-02-23 18:56 UTC, Rutherther commented on mcu/atmega-hal/src/usart.rs
> +> for crate::pac::USART {
I've added TODO.

2023-02-23 18:58 UTC, Rutherther commented on mcu/atmega-hal/src/usart.rs
> +        let ubrrh: u8 = ((baudrate.ubrr >> 8) & 0xFF) as u8;
You are absolutely right, changed to 0x0f and added a comment.

2023-02-23 22:46 UTC, Rahix commented on avr-hal-generic/src/wdt.rs
> +        $crate::paste::paste! {
Rust macros are arcane magic, avoid them if you can ^^

2023-02-23 22:55 UTC, Rahix approved these changes
Perfect, thank you!

2023-02-23 22:58 UTC, merged