Support the SparkFun ProMini 5V
Rahix/avr-hal pull request #435
Opened 2023-09-04 05:51 UTC by norepimorphism

This PR adds a new feature to *arduino-hal*, `sparkfun-promini-5v`, and a new board to ravedude, `promini-5v`. It is a copy, in nearly all respects, of the Arduino Nano implementation. I have used [this datasheet](https://cdn.sparkfun.com/assets/d/5/2/f/0/ProMini16MHzv2.pdf) as reference.

In the ravedude board config `SparkFunProMini5V` I  have implemented `guess_port` with a VID/PID pair I derived experimentally from my Pro Mini*, but I'm not sure if that is the correct approach.

Related issue: #425

*It is listed in <http://www.linux-usb.org/usb.ids> as "FT232 Serial (UART) IC" by FTDI.

2023-09-04 16:55 UTC, norepimorphism commented
An alternative to my implementation of the `sparkfun-promini-5v` feature in *arduino-hal* is to have it simply imply the `arduino-nano` feature (and I prefer this for the sake of maintenance). My belief is that the Pro Mini 5V is functionally an Arduino Nano sans an onboard FT232R.

2023-10-19 22:59 UTC, Rahix requested changes
Hi, so sorry for the delay here...

> An alternative to my implementation of the sparkfun-promini-5v feature in arduino-hal is to have it simply imply the arduino-nano feature

I think I actually prefer the way you've done things right now. This means that both boards are really and truly handled separately and a change introduced for one of them doesn't unintentionally affect the other.

I have one comment about the FTDI VID/PID, see below. Apart from that, everything else LGTM!

2023-10-19 22:59 UTC, Rahix commented on ravedude/src/board.rs
> +        Some(find_port_from_vid_pid_list(&[(0x0403, 0x6001)]))
We can't assume that any old FTDI chip is a sparkfun pro mini 5v.  The `guess_port` should only be populated when there is a unique VID/PID that identifies this board without any doubt.

```suggestion
        Some(Err(anyhow::anyhow!("Not able to guess port")))
```

2023-10-23 20:59 UTC, norepimorphism commented
No worries, and sorry I didn't see your reply until now. I'll commit that change when I get home.

2023-10-24 22:09 UTC, Rahix approved these changes
Thanks!

2023-10-24 22:17 UTC, merged