[ravedude] add output modes, newline after n bytes or after char
Rahix/avr-hal pull request #549
Opened 2024-05-19 22:45 UTC by tippfehlr

This helps when working with non-ascii output.

Other solutions:

- use another serial console: too much context switching for me, having the serial console in watch mode is way better.
- use ravedude and pipe into hexdump or xxd: they only handle streamed data line by line, meaning the data is not printed immediately. They also can’t add newlines.

2024-06-08 11:54 UTC, Rahix commented
Thanks a lot for your contribution!  I like this change a lot.

Right now, we are doing a rather large rework of ravedude in #522.  I'll get back to your PR once that work is finished, otherwise things will get a bit too messy.  I don't expect a lot of conflicts with your changes, though.

2025-04-24 00:00 UTC, Rahix commented
> I keep output-mode as a cli override?

Yeah, I think adding a CLI override is a good idea.

2025-04-26 21:41 UTC, Rahix requested changes
Thanks a lot for picking this up again!

I have a few comments, see below :)  Please also check the CI after updating, it currently seems to throw some error.

2025-04-26 21:41 UTC, Rahix commented on ravedude/src/console.rs
> +                            // don’t execute in ascii mode, ascii is unreachable here
this comment should be dropped?  the unreachable is clear from the match above.

2025-04-26 21:41 UTC, Rahix commented on ravedude/src/config.rs
> +    pub newline_after: Option<u8>,
I think I would handle these via a method on `RavedudeGeneralConfig` to solve the same handling issues as with `OutputMode`.  Right now the parsing, validation, and defaulting of these settings is littered over many places.

```rust
pub enum NewlineMode {
    /// Break lines when encountering this byte
    On(u8),
    /// Break lines after this many bytes
    After(usize),
}

impl RavedudeGeneralConfig {
    pub fn newline_mode(&self) -> anyhow::Result<NewlineMode> {
        if self.newline_on.is_some() && self.newline_after.is_some() {
            anyhow::bail!("newline_on and newline_after cannot be used at the same time");
        }

        if let Some(on_str) = self.newline_on.as_ref() {
            Ok(NewlineMode::On(parse_newline_on(on_str)?))
        } else if let Some(after) = self.newline_after {
            Ok(NewlineMode::After(usize::from(after)))
        } else {
            // default newline mode
            Ok(NewlineMode::After(16))
        }
    }
}
```

You then call this method once in `main` and pass the `NewlineMode` value to `console::open()`.

2025-04-26 21:41 UTC, Rahix commented on ravedude/src/console.rs
> +    };
I assume this is a fancyness feature to print output in groupings of 4 when the `newline-after` value allows for this? :)

Such a piece of code screams for the use of an `Option` instead of a `bool` value.  This way you eliminate possible bugs by forgetting to check the `bool`.

```rust
// assuming the `NewlineMode` discussed above
let space_after = match newline_mode {
    NewlineMode::After(after) if after % 4 == 0 => Some(4),
    _ => None,
}
```

...and then further down, the use of this value becomes:

```rust
if let Some(after) = space_after {
    if byte_count % after == 0 {
        write!(stdout, " ").unwrap();
    }
}
```

or alternatively:

```rust
if matches!(space_after, Some(after) if byte_count % after == 0) {
    write!(stdout, " ").unwrap();
}
```

2025-04-26 21:41 UTC, Rahix commented on ravedude/src/main.rs
> +fn parse_newline_on(s: &str) -> Result<char, anyhow::Error> {
The `newline_on` value shouldn't be a `char`, but rather a `u8`.  `char` can represent arbitrary unicode codepoints, but really we want to compare bytes here.

2025-04-26 21:44 UTC, Rahix commented on ravedude/src/main.rs
> +}
On that note, I have one more change to improve this:

```rust
if let Ok(n) = u8::from_str_radix(&s[2..4], 16) {
    return Ok(n);
} else {
    bail!("invalid hex byte");
}
```

can be shortened to

```rust
return u8::from_str_radix(&s[2..4], 16).context("invalid hex byte in `newline-on`");
```

2025-04-26 21:52 UTC, tippfehlr commented
Thanks for the very thorough review, I’ll do that tomorrow. I was happy that my git rebase was successful and also still want to test this with an Arduino.

2025-04-27 13:47 UTC, tippfehlr commented on ravedude/src/console.rs
> +    );
I removed this completely since it’s obvious anyways.

2025-04-27 14:07 UTC, tippfehlr commented
That should address all your comments, I didn’t test it yet though.

2025-04-27 17:03 UTC, Rahix commented
Please run `cargo fmt` on the code, there seem to be a few formatting issues.  Let me know once you have tested it :)

2025-05-02 21:48 UTC, tippfehlr commented
That should do it, sorry for not formatting it right away. I also tested it now, no problems (only that the console info was printed twice, fixed in the last commit. forgot to mention that in the commit message though)

2025-06-01 15:31 UTC, tippfehlr commented
Is something blocking this?

2025-06-02 21:35 UTC, Rahix commented
Hi,

> Is something blocking this?

no, just me not having found the time to go over it again, yet.  Will ping you in the coming days once I had the opportunity!

2025-06-02 22:00 UTC, tippfehlr commented
Ah, take your time! I didn't get what your push was for, that's why I asked.

2025-06-02 22:09 UTC, Rahix commented
> I didn't get what your push was for, that's why I asked.

That was just a rebase to ensure CI is still passing with things that had happened on `main`. :)

2025-06-05 05:29 UTC, Rahix commented on ravedude/src/main.rs
> +
This check can now be dropped that we ensure the same thing in `RavedudeGeneralConfig::newline_mode()`, right?

2025-06-14 16:06 UTC, tippfehlr commented on ravedude/src/main.rs
> +
true, good catch!

2025-08-31 21:06 UTC, Rahix commented on ravedude/src/config.rs
> +}
One more tiny thing I just noticed during testing:  The config options currently require to be spelled like `Ascii` instead of `ascii`.  This is easy to fix, so I'll take care of it myself to not block this any longer:

```suggestion
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Default, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum OutputMode {
    #[default]
    Ascii,
    Hex,
    Dec,
    Bin,
}
```

2025-08-31 21:13 UTC, merged

2025-09-01 00:40 UTC, tippfehlr commented
Thanks for merging this! I just update the AUR package to 0.2.1 too.